import = [
    "~/.config/alacritty/themes/themes/everforest_light.toml"
]

[font]
size=13.0

[scrolling]
history = 100000

[selection]
save_to_clipboard= true

[font.normal]
family = "Inconsolata NerdFont Mono"

